### ISSUE TITLE
Possible to add my own CSS includes after "WebResource.axd"?

### ISSUE THREAD

**Issue by UweKeim** [DevExpress/AjaxControlToolkit#399]
### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce 

I want to be able to override styles from (e.g.) the Tab Control.

Since your [`RegisterCssReferences` method](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/ToolkitResourceManager.cs#L199) seems to always append the "WebResource.axd" calls always to the very end of the HTML head tag, I can never include my own CSS files after that.

```csharp
var link = new HtmlLink();
link.Href = href;
link.Attributes.Add("type", "text/css");
link.Attributes.Add("rel", "stylesheet");
header.Controls.Add(link);
```

### My question

Is it possible to add my own CSS reference _below_ your "WebResource.axd" links inside the HTML head?

### Browser(s) used

Google Chrome

### A site deployment method
- [X] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @UweKeim,

Would you please clarify: are you trying to change default control's styles when using it in a normal way or you created a derived control and want to override styles from a parent class?

**Comment by UweKeim** [comment]
Thanks, @MikhailTymchukDX.

Yes, I want to override styles for e.g. the tab control. 

Therefore my style sheet link must come _after_ your "WebResource.axd" style sheet link.

Currently I see no way, as described above.

**Comment by UweKeim** [comment]
I do think a workaround would be to put my CSS link inside the body, instead of the head, but [it is not recommended](https://stackoverflow.com/q/4957446/107625).

**Comment by MikhailTymchukDX** [comment]
@UweKeim 
I don't completely understand your scenario.

If you need to specify a CSS for some control, you can set a `CssClass` property if such property exists for that control.
This property exists for the TabContainer, so you can specify a CSS class for it:
```aspx
<ajaxToolkit:TabContainer runat="server" CssClass="myclass" />
```

**Comment by UweKeim** [comment]
In previous (previous, previous, ...) releases of AjaxControlToolkit, I was able to directly specify my own overrides for classes like e.g. `ajax__tab`, `ajax__tab_outer`, etc.

Now, after updating to the latest version, I'm not able to do this anymore.

For references, this is the complete content of my "tabs.css":

```css
/* scrolling */
.ajax__scroll_horiz {
    overflow-x: scroll;
}

.ajax__scroll_vert {
    overflow-y: scroll;
}

.ajax__scroll_both {
    overflow: scroll;
}

.ajax__scroll_auto {
    overflow: auto;
}

/* plain theme */
.ajax__tab_plain .ajax__tab_outer {
    text-align: center;
    vertical-align: middle;
    background-color: #F9F9F9;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 8px;
    padding-right: 8px;
    border-right: solid 4px white;
}

.ajax__tab_plain .ajax__tab_inner {
}

.ajax__tab_plain .ajax__tab_body {
    background-color: white; /* #F7FCF4 */
    border-top: solid 1px #EBEBEB;
    border-bottom: solid 1px #EBEBEB;
    padding-top: 18px;
    padding-bottom: 0px;
}

.ajax__tab_plain .ajax__tab_header {
}

.ajax__tab_plain .ajax__tab_active .ajax__tab_outer {
    background-color: #EBEBEB;
    /*font-weight:bold;*/
}

.ajax__tab_plain .ajax__tab_active .ajax__tab_outer .ajax__tab_tab {
    color: black !important;
}

.ajax__tab_container {
    padding-top: 12px;
}

.ajax__tab_plain .ajax__tab_tab {
    color: rgb(100,100,100);
}
```
