### ISSUE TITLE
TabContainer is not showing css in V 18.1

### ISSUE THREAD

**Issue by casheets** [DevExpress/AjaxControlToolkit#410]
AJAX Control Toolkit \18.1.0.0\

The installation method
- [ ] NuGet package

I am using Visual Studio 2010 with Chrome as the browser. I was previously using Version 4.1.40412.2, but have upgraded to Version 18.1.00. After the upgrade, the TabContainer styles are no longer working.  It appears that the default css for the TabContainer is not being over-written. Could you help me see what I am missing?

The html for the TabContainer is: <asp:TabContainer ID="TabContainer1" runat="server" ActiveTabIndex="0" CssClass="MyTabStyle" >

The style sheet contains:
.MyTabStyle .ajax__tab_header{
    display: inline-block;
    color: #4682b4;
    font-family: Calibri;
    font-size: 34px;
    font-weight: bold;
    background-color: #ffffff;
    background: url("images/tab_hover.gif") repeat-x;
}
.MyTabStyle .ajax__tab_header:after {
    clear: both;
}
.MyTabStyle .ajax__tab_header:before, .MyTabStyle .ajax__tab_header:after {
    content: "";
    display: table;
}

/*Body*/
.MyTabStyle .ajax__tab_body
{
    border: 1px solid #b4cbdf;
    padding-top: 0px;
}

/*Tab Active*/
.MyTabStyle .ajax__tab_active .ajax__tab_tab
{
    color: #ffffff;
    background: url("images/tab_active.gif") repeat-x;
    height: 20px;
    margin: 0px !important;
}

.MyTabStyle .ajax__tab_active .ajax__tab_inner
{
    color: #ffffff;
    background: url("images/tab_left_active.gif") no-repeat left;
    padding-left: 10px;
}

.MyTabStyle .ajax__tab_active .ajax__tab_outer
{
    color: #ffffff;
    background: url("images/tab_right_active.gif") no-repeat right;
    padding-right: 6px;
}

/*Tab Hover*/

.MyTabStyle .ajax__tab_hover .ajax__tab_tab
{
    color: #000000;
    background: url("images/tab_hover.gif") repeat-x;
    height: 20px;
}

.MyTabStyle .ajax__tab_hover .ajax__tab_inner
{
    color: #000000;
    background: url("images/tab_left_hover.gif") no-repeat left;
    padding-left: 10px;
}

.MyTabStyle .ajax__tab_hover .ajax__tab_outer
{
    color: #000000;
    background: url("images/tab_right_hover.gif") no-repeat right;
    padding-right: 6px;
}

The result now looks like this:
![image](https://user-images.githubusercontent.com/36202227/35882550-3388a9a6-0b4a-11e8-9ebb-05a009574274.png)

Previously the result was:
![image](https://user-images.githubusercontent.com/36202227/35882572-4322040c-0b4a-11e8-8531-610185c64144.png)

### Browser(s) used
Chrome

### A site deployment method
- [ ] IIS

Thank you for your assistance.

**Comment by MikhailTymchukDX** [comment]
Hi @casheets,

I made the sample project based on your markup to see what causes this issue: 
[TabsTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1702800/TabsTest.zip)

I can see that Tabs' default appearance is changed, but it's still unclear to me if a custom style is applied in the way you expect.

Would you please provide your own sample project with an old version of the toolkit so we can see the difference?

**Comment by casheets** [comment]
Thank you for your response.

I've attached a .zip file with an example of the older version of the Ajax Toolkit Tab Panels. Something to keep in mind, I'm using Visual Studio 2010, vb.


Thanks again for your help.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by MikhailTymchukDX** [comment]
Hi @casheets 
When you send a reply via e-mail, no attachments are added to the issue.
Would you please add it via github web UI?

**Comment by casheets** [comment]
I've attached a .zip file with an example of the older version of the Ajax Toolkit Tab Panels. Also, just something to keep in mind, I'm using Visual Studio 2010, vb.
Thanks for your help.
[TabPanels.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1724450/TabPanels.zip)

**Comment by MikhailTymchukDX** [comment]
Hi @casheets 
Thank you very much for the sample project!

Tabs markup is changed since v4.1.40412.2, so your CSS rules were not applied properly.

For example, in the old version of the toolkit, class hierarchy for a tab header text was the following:
```
MyTabStyle ajax__tab_header
  ajax__tab_active
    ajax__tab_outer
      ajax__tab_inner
        ajax__tab_tab ('span' element)
```

In the latest version of the toolkit class hierarchy is different:
```
MyTabStyle ajax__tab_xp ajax__tab_container ajax__tab_default
  ajax__tab_header
    ajax__tab_active ajax__tab_active
      ajax__tab_outer
        ajax__tab_inner
          ajax__tab_tab (`a` element)
```

So, I added `.ajax__tab_default .ajax__tab_header` to every rule:
```css
.MyTabStyle.ajax__tab_default .ajax__tab_header{
	color: #4682b4;
	font-family: Calibri;
	font-size: 14px;
	font-weight: bold;
	background-color: #ffffff;
	margin-left: 0px;
}

/*Body*/
.MyTabStyle .ajax__tab_body
{
	border: 1px solid #b4cbdf;
	padding-top: 0px;
}

/*Tab Active*/
.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_active .ajax__tab_tab
{
	color: #ffffff;
	background: url("images/tab_active.gif") repeat-x;
	height: 20px;
	margin: 0px !important;
	min-width: 80px;
	max-width: 200px;
	padding-left: 3px;
}
.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_active .ajax__tab_inner
{
	background: url("images/tab_left_active.gif") no-repeat left;
	padding-left: 3px;
}

.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_active .ajax__tab_outer
{
	background: url("images/tab_right_active.gif") no-repeat right;
	padding-right: 6px;
	margin-right: 1px;
}

/*Tab Hover*/
.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_hover .ajax__tab_tab
{
	color: #FFFFFF;
	background: url("images/tab_hover.gif") repeat-x;
	height: 20px;
	margin: 0px !important;
	min-width: 80px;
	max-width: 200px;
	padding-left: 3px;
}

.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_hover .ajax__tab_inner
{
	background: url("images/tab_left_hover.gif") no-repeat left;
	padding-left: 3px;
}

.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_hover .ajax__tab_outer
{
	background: url("images/tab_right_hover.gif") no-repeat right;
	padding-right: 6px;
	margin-right: 1px;
}

/*Tab Inactive*/
.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_tab
{
	color: #666666;
	background: url("images/tab_Inactive.gif") repeat-x;
	height: 20px;
	margin: 0px !important;
	min-width: 80px;
	max-width: 200px;
	padding-left: 3px;
}

.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_inner
{
	background: url("images/tab_left_inactive.gif") no-repeat left;
	padding-left: 3px;
}

.MyTabStyle.ajax__tab_default .ajax__tab_header .ajax__tab_outer
{
	background: url("images/tab_right_inactive.gif") no-repeat right;
	padding-right: 6px;
	margin-right: 1px;
}
```
Tab headers are located a bit lower than they should be, but I hope you get the idea.

Here is the updated sample project: [TabPanels.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1727529/TabPanels.zip)

Feel free to comment if you need further assistance.
