### ISSUE TITLE
TabContainer not showing tab pages correctly when css added

### ISSUE THREAD

**Issue by rachaeloffaly** [DevExpress/AjaxControlToolkit#5]
I have a tabcontainer with several tabpanels within it, it shows fine when no css is added, but as soon as I add the css the tabpanels show to the right of the tabs instead of underneath

![tabcontrol_error](https://cloud.githubusercontent.com/assets/17780706/13698618/06ff7228-e76d-11e5-95af-b75d5527a2ed.png)

**Comment by dparks2** [comment]
I also have this problem when upgrading from 15.1.4 to 16.1.0. Exactly as displayed above. tab panels are pushed out to the right of the tabs and not below.

**Comment by jcm4101** [comment]
I also see this problem... bump

**Comment by rachaeloffaly** [comment]
if this is by design how do i get them to show normally again ??

**Comment by MikhailTymchukDX** [comment]
This behavior is caused by the [27989](https://ajaxcontroltoolkit.codeplex.com/workitem/27989) issue fix.

When you set up the `CssClass `attribute for a TabContainer it overwrites the default `ajax__tab_xp` class with a custom class, thus making the `.ajax__tab_xp .ajax__tab_header` selector invalid (see [Tabs.css](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Styles/Tabs.css)).

Hence, you need to maintain these CSS properties when overriding the default `ajax__tab_xp` class.
Assuming you have custom `tabs` CSS class, add the following CSS declaration:

```css
.tabs .ajax__tab_header:after {
	clear: both;
}

.tabs .ajax__tab_header:before, .tab .ajax__tab_header:after {
	content: "";
	display: table;
}
```

**Comment by dparks2** [comment]
I'm sorry, I've been messing with the css suggestions above all morning and cannot get them to work. I've even removed my css file and swapped in the entire Tabs.css class referenced above as a whole, to no avail.
This is still a problem for me and I've rolled back again to 15.1.4.
Did the above suggested fix work for anyone else?

**Comment by rachaeloffaly** [comment]
No I couldn't get it to work either and I tried the same and replaced the css wit the one reference aswell but no luck

I've had to roll back to 15.1.3 due to an issue with modal popup in 15.1.4

**Comment by dparks2** [comment]
@rachaeloffaly , thank for the feedback, and for what it's worth, I found 15.1.2 to be more stable than 15.1.3 as the later introduced multiple issues with calendar extenders and format extenders that were fixed for me in 15.1.4.

**Comment by MikhailTymchukDX** [comment]
There was a typo in the CSS code provided before. The correct code is the following:
```css
.tabs .ajax__tab_header:after {
    clear: both;
}

.tabs .ajax__tab_header:before, .tabs .ajax__tab_header:after {
    content: "";
    display: table;
}
```

I also attached a sample project to show that this workaround works: [TabsTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/175481/TabsTest.zip)
